# Site settings
name: Von Site
email: yanwengong7@gmail.com
author: Yanwen Gong
url: 
resume_site: 
github: https://github.com/yanwengong/
baseurl: ""
description: No time for description.
meta_description: 
motto: Think. Work. Speak.
banner: 业精于勤荒于嬉 行成于思毁于随


#permalink: /:year/:month/:day/:title/
markdown: kramdown
permalink: pretty

#paginate: 10

#include: ['jekyll-paginate', 'rouge']
#exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yanwengong

# Build settings
highlighter: rouge
kramdown:
    auto_ids: true
    input: GFM
    syntax_highlighter: rouge


FB:
  comments :
    provider : disqus
    disqus :
        short_name : zangshayang1-github-io
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
